global using InveonCourseApp.Backend.Core.Enums;
global using InveonCourseApp.Backend.Dtos.AuditablePersonBaseEntityDtos;
global using InveonCourseApp.Backend.Dtos.CategoryDtos;
global using InveonCourseApp.Backend.Dtos.CourseDtos;
global using InveonCourseApp.Backend.Dtos.CourseOrderDtos;
global using InveonCourseApp.Backend.Dtos.OrderDtos;
global using InveonCourseApp.Backend.Dtos.StudentDtos;
global using InveonCourseApp.Backend.Dtos.StudentCourseDtos;
global using InveonCourseApp.Backend.Dtos.TrainerDtos;