global using Microsoft.AspNetCore.Authorization;
global using Microsoft.AspNetCore.Localization;
global using Microsoft.AspNetCore.Mvc;
global using Microsoft.Extensions.Localization;
global using System.Globalization;

global using InveonCourseApp.Backend.API.Extensions;
global using InveonCourseApp.Backend.BackgroundJobs.Extensions;
global using InveonCourseApp.Backend.Business.Abstract.Services.Abstract;
global using InveonCourseApp.Backend.Business.Concrete.Extensions;
global using InveonCourseApp.Backend.Cache.Extensions;
global using InveonCourseApp.Backend.Core.Constants;
global using InveonCourseApp.Backend.Core.Enums;
global using InveonCourseApp.Backend.Core.Extensions;
global using InveonCourseApp.Backend.Core.Resources;
global using InveonCourseApp.Backend.DataAccess.Extensions;
global using InveonCourseApp.Backend.DataAccess.Concrete.Extensions;
global using InveonCourseApp.Backend.Dtos.IdentityUserDtos;
global using InveonCourseApp.Backend.Queue.Extensions;